// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (87.21s total).
export const FPS = 30;
export const NARRATION_SECONDS = 87.21;
export const SCENES = [
  {
    "k": "hook",
    "s": 10.12,
    "marks": {
      "sub": 46,
      "pct": 96,
      "never": 145,
      "brand": 184
    }
  },
  {
    "k": "sweep",
    "s": 12.6,
    "marks": {
      "f0": 70,
      "f1": 121,
      "f2": 161,
      "f3": 201,
      "f4": 245,
      "f5": 286,
      "f6": 325
    }
  },
  {
    "k": "p1",
    "s": 8.45,
    "marks": {
      "chip": 80
    }
  },
  {
    "k": "p2",
    "s": 11.05,
    "marks": {
      "chip": 188
    }
  },
  {
    "k": "p3",
    "s": 9.88,
    "marks": {
      "chip": 87
    }
  },
  {
    "k": "p4",
    "s": 9.72,
    "marks": {
      "chip": 121
    }
  },
  {
    "k": "adds",
    "s": 8.9,
    "marks": {
      "chip": 112,
      "show": 233
    }
  },
  {
    "k": "outcome",
    "s": 7.26,
    "marks": {
      "l0": 32,
      "l1": 82,
      "l2": 133
    }
  },
  {
    "k": "cta",
    "s": 9.23,
    "marks": {
      "btn": 177,
      "url": 218
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
