// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (89.21s total).
export const FPS = 30;
export const NARRATION_SECONDS = 89.21;
export const SCENES = [
  {
    "k": "hook",
    "s": 14.71,
    "marks": {
      "sub": 80,
      "pct": 130,
      "never": 173,
      "brand": 318
    }
  },
  {
    "k": "sweep",
    "s": 13.91,
    "marks": {
      "f0": 85,
      "f1": 155,
      "f2": 210,
      "f3": 255,
      "f4": 315,
      "f5": 357
    }
  },
  {
    "k": "p1",
    "s": 9.94,
    "marks": {
      "chip": 126
    }
  },
  {
    "k": "p2",
    "s": 11.23,
    "marks": {
      "chip": 136
    }
  },
  {
    "k": "p3",
    "s": 10.9,
    "marks": {
      "chip": 86
    }
  },
  {
    "k": "adds",
    "s": 12.19,
    "marks": {
      "chip": 191,
      "show": 309
    }
  },
  {
    "k": "outcome",
    "s": 7.99,
    "marks": {
      "l0": 36,
      "l1": 96,
      "l2": 158
    }
  },
  {
    "k": "cta",
    "s": 8.35,
    "marks": {
      "btn": 146,
      "url": 189
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
